version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres
    restart: always
    env_file:
      - ./app/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code/app

volumes:
  postgres_data: